{% set name = "cx_Logging" %}
{% set version = "3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba8a7465facf7b98d8f494030fb481a2e8aeee29dc191e10383bb54ed42bdb34
  patches:
    - add-include.patch
    - pr6.patch
    - pr7.patch

build:
  number: 7
  skip: True  # [not win]
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip
    - setuptools
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - cx_Logging
  commands:
    - echo CONDA_PREFIX=%CONDA_PREFIX%
    - cd %CONDA_PREFIX% && dir cx_Logging*.* /s

about:
  home: https://github.com/anthony-tuininga/cx_Logging
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Python and C interfaces for logging'

extra:
  recipe-maintainers:
    - marcelotduarte
