{% set name = "cx_Logging" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bdbad6d2e6a0cc5bef962a34d7aa1232e88ea9f3541d6e2881675b5e7eab5502

build:
  number: 1
  skip: true  # [not win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - cx_Logging
  commands:
    - echo CONDA_PREFIX=%CONDA_PREFIX%
    - cd %CONDA_PREFIX% && dir cx_Logging*.* /s
    - pip check

about:
  home: https://github.com/anthony-tuininga/cx_Logging
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python and C interfaces for logging

extra:
  recipe-maintainers:
    - marcelotduarte
