schema_version: 1

context:
  name: cx_Logging
  version: 3.2.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name|lower }}-${{ version }}.tar.gz
  sha256: 812665ae5012680a6fe47095c3772bce638e47cf05b2c3483db3bdbe6b06da44

build:
  number: 4
  skip: not win
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

tests:
  - python:
      imports:
        - cx_Logging
  - script:
      - echo CONDA_PREFIX=%CONDA_PREFIX%
      - cd %CONDA_PREFIX% && dir cx_Logging*.* /s
      - pip check

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Python and C interfaces for logging
  homepage: https://github.com/anthony-tuininga/cx_Logging

extra:
  recipe-maintainers:
    - marcelotduarte
